# Generated by Django 6.0.3 on 2026-03-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='quadros/')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Ex: 1500.00', max_digits=10)),
                ('data_criacao', models.DateField()),
            ],
        ),
    ]
